services:
  - type: web
    name: HTCode-udaan
    env: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: "3000"
